import pandas as pd
in_file = '/Volumes/Echo/GIS/projects/streetview/tasks/201402_crashes_streetratings/exchange/from_20140108_steve/newyork_with_rating_date.csv'
out_file = '/Volumes/Echo/GIS/projects/streetview/tasks/201402_crashes_streetratings/exchange/from_20140108_steve/newyork_with_rating_date_uid.csv'
df = pd.read_csv(in_file)
df['svsuid'] = df['User'].apply(str) + df['Segment ID'].apply(str)
df['segmid'] = df['Segment ID']

droplist = ['User','Segment ID','Meta.1','Meta.1_impediment','Meta.2','Meta.2_impediment','Meta.6','Meta.6_impediment','Meta.7','Meta.7_impediment','PEDS.3','PEDS.3_impediment','Minn-Irvine.9','Minn-Irvine.9_impediment','PEDS.23.2','PEDS.23.2_impediment','Minn-Irvine.2','Minn-Irvine.2_impediment','Minn-Irvine.4','Minn-Irvine.4_impediment','PEDS.23.4','PEDS.23.4_impediment','PEDS.23.3','PEDS.23.3_impediment','Minn-Irvine.8','Minn-Irvine.8_impediment','Minn-Irvine.21','Minn-Irvine.21_impediment','PEDS.14','PEDS.14_impediment','Minn-Irvine.151','Minn-Irvine.151_impediment','PEDS.19','PEDS.19_impediment','Minn-Irvine.108','Minn-Irvine.108_impediment','Minn-Irvine.123','Minn-Irvine.123_impediment','PEDS.24.1','PEDS.24.1_impediment','PEDS.4.1','PEDS.4.1_impediment','PEDS.12','PEDS.12_impediment','PEDS.6','PEDS.6_impediment','PEDS.9','PEDS.9_impediment','PEDS.8.2','PEDS.8.2_impediment','PEDS.35','PEDS.35_impediment','Minn-Irvine.159','Minn-Irvine.159_impediment','Minn-Irvine.178','Minn-Irvine.178_impediment','Streetview.3','Streetview.3_impediment','Streetview.4','Streetview.4_impediment','Streetview.5','Streetview.5_impediment','Streetview.6','Streetview.6_impediment','Streetview.7','Streetview.7_impediment','CCAHS.2','CCAHS.2_impediment','CCAHS.4','CCAHS.4_impediment','CCAHS.5','CCAHS.5_impediment','CCAHS.8','CCAHS.8_impediment','CCAHS.9','CCAHS.9_impediment','PEDS.1.4','PEDS.1.4_impediment','PEDS.1.5','PEDS.1.5_impediment','PEDS.1.6','PEDS.1.6_impediment','PEDS.1.7','PEDS.1.7_impediment','PEDS.1.8','PEDS.1.8_impediment','Minn-Irvine.33','Minn-Irvine.33_impediment','Minn-Irvine.34','Minn-Irvine.34_impediment','Minn-Irvine.127','Minn-Irvine.127_impediment','Minn-Irvine.132','Minn-Irvine.132_impediment','MIUDQ.10','MIUDQ.10_impediment','PEDS.33','PEDS.33_impediment','Minn-Irvine.130','Minn-Irvine.130_impediment','Minn-Irvine.22','Minn-Irvine.22_impediment','Minn-Irvine.17','Minn-Irvine.17_impediment','Minn-Irvine.119','Minn-Irvine.119_impediment','Minn-Irvine.120','Minn-Irvine.120_impediment','MIUDQ.18','MIUDQ.18_impediment','PEDS.26.1','PEDS.26.1_impediment','PEDS.2','PEDS.2_impediment','PEDS.28','PEDS.28_impediment','PHDCN.1','PHDCN.1_impediment','PHDCN.2','PHDCN.2_impediment','PHDCN.3','PHDCN.3_impediment','PHDCN.4','PHDCN.4_impediment','PHDCN.5','PHDCN.5_impediment','PHDCN.6','PHDCN.6_impediment','PHDCN.7','PHDCN.7_impediment']
df = df.drop(droplist, axis=1)
df.to_csv(out_file, index=False)